name: Lint and Fix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.23' # Update to the version you are using

      - name: Install dependencies
        run: |
          go mod tidy
          go install mvdan.cc/gofumpt@latest
          go install github.com/daixiang0/gci@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
      - name: Run lint
        run: make lint

      - name: Fix gci
        run: make fix-gci

      - name: Fix gofumpt
        run: make fix-gofumpt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Fix linting issues" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
